### ISSUE TITLE
Catch errors in parser handlers

### ISSUE THREAD

**Issue by iftheshoefritz** [iftheshoefritz/solargraph-rails#13]
When RubyParser calls `on_module`, `on_class` etc, the code that its client runs could raise an error and kill the whole process. It seems better that if one handler fails, other handlers should still be able to run. Rescue errors but make sure to log them at ERROR level.

**Comment by alisnic** [comment]
@iftheshoefritz new solargraph-rails code has catches for each of its modules so this should be a problem
