### ISSUE TITLE
Add rake task to copy over the solargraph rails gist

### ISSUE THREAD

**Issue by julianrubisch** [iftheshoefritz/solargraph-rails#18]
from https://gist.github.com/castwide/28b349566a223dfb439a337aea29713e

**Comment by iftheshoefritz** [comment]
@julianrubisch is this still relevant since @alisnic merged ARC here?

**Comment by julianrubisch** [comment]
I don't know honestly! I've put it in a railsbyte for now...

**Comment by alisnic** [comment]
@iftheshoefritz annotations are not needed in the project as they are part of the gem
