### ISSUE TITLE
Getting "uninitialized constant Solargraph::Convention (NameError)" on solargraph 0.41?

### ISSUE THREAD

**Issue by julianrubisch** [iftheshoefritz/solargraph-rails#21]
```
solargraph-rails-0.2.1/lib/solargraph-rails.rb:11:in `<module:Rails>': uninitialized constant Solargraph::Convention (NameError)
```

Just upgraded my solargraph installation, and solargraph-rails ceased working.

Happy to dive into it deeper should anything be unclear

**Comment by iftheshoefritz** [comment]
I can't reproduce with Ruby 3 / sg-rails 0.2.1 / sg 0.41.1, what are you running? If you have time to dig further, can you see what happens if you start from [your Railsbyte](https://railsbytes.com/templates/zr4skp)?

**Comment by iftheshoefritz** [comment]
Julian indicates that the error went away without problems
