### ISSUE TITLE
Why the strict dependency version policies in the gemspec?

### ISSUE THREAD

**Issue by pelletencate** [iftheshoefritz/solargraph-rails#22]
The v0.2.2 pre-releases currently cannot be used by any rails version other than 6.1.3 due to the requirement of active_support.

Changelog says you need it for simple string helpers that have been in activesupport for years. If that's the case, then why depend on such a strict version?

A similar argument could be made for the fact that Solargraph itself cannot be used on the latest version when using solargraph-rails on v0.2.1. 

Wouldn't it be better to use activesupport `>= 6.0.0` (or even 5 if you support Rails 5), and solargraph `>= 0.41.1`?

**Comment by iftheshoefritz** [comment]
Good point! I'll loosen the Rails dependency when I get the chance.

The solargraph strict dependency was to save people from bugs in solargraph that actually broke this gem.

**Comment by iftheshoefritz** [comment]
@pelletencate I released v0.2.1.1 and v0.2.2.pre.4 with loosened requirements. Let me know if they get you where you need to be?

**Comment by pelletencate** [comment]
That looks a lot more manageable, thanks!
