### ISSUE TITLE
Can the solargraph dependency be upgraded to  0.47.x?

### ISSUE THREAD

**Issue by vassyz** [iftheshoefritz/solargraph-rails#48]
The dependabot PR keep switching between upgrading `solargraph-rails` from 0.3.1 to 1.0.1 and `solargraph` from 0.44.3 to 0.47.2 (and downgrading `solargraph-rails` back to 0.3.1). This is because `solargraph-rails` version 0.3.1 has `solargraph (>= 0.41.1)` as the version constraint and 1.0.1 has `solargraph (~> 0.44.2)`.

**Comment by iftheshoefritz** [comment]
The version is completely unpinned in 1.1.0, we'll see how well completely removing it works for a while :)
