### ISSUE TITLE
Tag 1.0.1 available on rubygems but not here

### ISSUE THREAD

**Issue by asadakbar** [iftheshoefritz/solargraph-rails#52]
Just a heads up that I see 1.0.1 is available through ruby gems https://rubygems.org/gems/solargraph-rails/versions/1.0.1 but not listed under tags here in the repo. Maybe it got pulled mistakenly when 1.0.0 got pulled?

**Comment by iftheshoefritz** [comment]
Thanks for alerting me, this is fixed!
