### ISSUE TITLE
Solargraph shows error `uninitialized constant Bundler::SharedHelpers`

### ISSUE THREAD

**Issue by johncardiologs** [iftheshoefritz/solargraph-rails#70]
**Describe the bug**

Adding solargraph-rails to my rails project leads to solargraph crashing with error message:

```
[Error - 15:28:05.965] Request textDocument/definition failed.
  Message: [NameError] uninitialized constant Bundler::SharedHelpers
  Code: -32603 
```

**To Reproduce**
1. On an existing project with the latest `solargraph` gem installed, install latest `solargraph-rails` gem
2. Observe the error in the solargraph workspace.showOutput console when attempting to use solargraph features

**Expected behavior**
I expect the solargraph-rails gem to function correctly.

I've narrowed this down to specifically `solargraph-rails`, by removing the gem from my project and leaving only `solargraph`. I then bundle install, and solargraph works as expected.

I'm using ruby (installed via asdf) on version 3.3.0 without issues, on a rails app running version 7.1.3.
I have both the `solargraph` and `solargraph-rails` gems installed, with no version specification (latest).

```
❯ which solargraph
/Users/john/.asdf/shims/solargraph
```

In my project's `Gemfile.lock`, I see:
```
    solargraph (0.50.0)
    solargraph-rails (1.1.0)
      activesupport
      solargraph
```

I've tried reinstalling the `solargraph-rails` gem, without success.

For now, I will continue to use solargraph without the `solargraph-rails` gem.

**Comment by arashm** [comment]
Same issue. Removing `solargraph-rails` plugin makes solargraph work again.

**Comment by arashm** [comment]
I think this is most probably a bundler issue https://github.com/rubygems/rubygems/pull/7638
perhaps we have to wait for a bundler update.

**Comment by arashm** [comment]
Working fine again with the new version of bundler 2.5.11

**Comment by johncardiologs** [comment]
Works for me as well on bundler 2.5.11! Cheers :-)
